/**
 * Deploys to Cloudflare (PIN-0020). See `.codex/specs/deploy-cloudflare.md`.
 *
 * Two configs exist and neither can do this job alone:
 *
 * - `dist/server/wrangler.json` is regenerated by `npm run build`. It knows `main`, the
 *   assets directory and the bundling rules, but its D1 entry is `vite.config.ts`'s LOCAL
 *   placeholder. Editing it by hand is not a fix; the next build overwrites it.
 * - `wrangler.deploy.jsonc` knows the real database. It is also what the `wrangler d1` commands
 *   use, so the id has exactly one home.
 *
 * That file is deliberately NOT called `wrangler.json`: `@cloudflare/vite-plugin`
 * auto-discovers that name and merges it into the generated manifest, which produced two D1
 * entries on the same binding. The assertion below is what caught it.
 *
 * This merges the second into the first and deploys the result. That is the option the spec
 * warned would rot, because it depends on the shape of a file another tool owns — so it
 * asserts that shape and stops rather than deploying something surprising.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { readJsonc } from "./read-config.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const generatedPath = join(root, "dist/server/wrangler.json");
const rootPath = join(root, "wrangler.deploy.jsonc");
const mergedPath = join(root, "dist/server/wrangler.deploy.jsonc");

if (!existsSync(generatedPath)) {
  console.error("No dist/server/wrangler.json. Run `npm run build` first.");
  process.exit(1);
}

const generated = JSON.parse(readFileSync(generatedPath, "utf8"));
const ours = readJsonc(rootPath);

const expect = (condition, message) => {
  if (condition) return;
  console.error(
    `The generated manifest is not the shape this script expects: ${message}.\n` +
      "Wrangler or the build plugin has changed. Read dist/server/wrangler.json and update\n" +
      "scripts/deploy.mjs rather than working around it — nothing was deployed."
  );
  process.exit(1);
};

expect(Array.isArray(generated.d1_databases), "d1_databases is not an array");
expect(generated.d1_databases.length === 1, `expected exactly one D1 entry, found ${generated.d1_databases.length}`);
expect(generated.d1_databases[0].binding === "DB", `expected the binding to be DB, found ${generated.d1_databases[0].binding}`);
expect(typeof generated.main === "string", "main is missing");
expect(generated.assets?.directory, "the assets directory is missing");

const real = ours.d1_databases?.find((entry) => entry.binding === "DB");
expect(real, "wrangler.deploy.jsonc has no DB binding");
expect(
  real.database_id && !real.database_id.startsWith("PLACEHOLDER"),
  "wrangler.deploy.jsonc still holds a placeholder database_id — run `wrangler d1 create pinto`"
);

// `migrations_dir` is for the `d1 migrations` commands and means nothing to a deploy.
const binding = Object.fromEntries(Object.entries(real).filter(([key]) => key !== "migrations_dir"));
const merged = { ...generated, d1_databases: [binding] };
writeFileSync(mergedPath, JSON.stringify(merged, null, 2));

console.log(`Deploying worker "${merged.name}" with D1 ${binding.database_name} (${binding.database_id}).`);

const passthrough = process.argv.slice(2);
execFileSync("npx", ["wrangler", "deploy", "-c", mergedPath, ...passthrough], {
  cwd: root,
  stdio: "inherit",
});
